### ISSUE TITLE
"No data" from dashboards

### ISSUE THREAD

**Issue by sinankizar** [amir-am/Firewall-Monitoring#1]
Hello,

First of all I want to thank you for creating such dashboard and config files. 

I am using influx V2, Grafana 9.2 and telegraf 1.26

I have set the conf file and tested it and got results below:

telegraf --test --config /etc/telegraf/telegraf.d/fortigate.conf
2023-06-05T07:10:44Z I! Loading config: /etc/telegraf/telegraf.d/fortigate.conf
2023-06-05T07:10:44Z I! Starting Telegraf 1.26.3
2023-06-05T07:10:44Z I! Available plugins: 235 inputs, 9 aggregators, 27 processors, 22 parsers, 57 outputs, 2 secret-stores
2023-06-05T07:10:44Z I! Loaded inputs: snmp
2023-06-05T07:10:44Z I! Loaded aggregators:
2023-06-05T07:10:44Z I! Loaded processors:
2023-06-05T07:10:44Z I! Loaded secretstores:
2023-06-05T07:10:44Z W! Outputs are not used in testing mode!
2023-06-05T07:10:44Z I! Tags enabled: host=mat-tr-mntr
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr cpu_usage=0i,ha_auto_sync=2i,ha_mode=1i,hostname="MAT-TR-FW001.mat.local",memory_usage=50i,os_version="v7.2.4,build1396,230131 (GA.F)",uptime=398681665i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=42,ifName=WIFI_MAT_USER ifHighSpeed=0i,ifInErrors=0i,ifInOctets=1814708099i,ifOperStatus=1i,ifOutErrors=0i,ifOutOctets=3032211339i,ifType=209i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=33,ifName=port15 ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=2i,ifOutErrors=0i,ifOutOctets=0i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=41,ifName=WIFI_GUEST ifHighSpeed=0i,ifInErrors=0i,ifInOctets=3398990169i,ifOperStatus=1i,ifOutErrors=0i,ifOutOctets=2295644615i,ifType=209i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=30,ifName=port12 ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=2i,ifOutErrors=0i,ifOutOctets=0i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=10,ifName=port24 ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=2i,ifOutErrors=0i,ifOutOctets=0i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=36,ifName=l2t.root ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=1i,ifOutErrors=0i,ifOutOctets=152i,ifType=131i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=21,ifName=port3 ifHighSpeed=1000i,ifInErrors=0i,ifInOctets=2571903708i,ifOperStatus=1i,ifOutErrors=0i,ifOutOctets=3050399525i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=7,ifName=port21 ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=2i,ifOutErrors=0i,ifOutOctets=0i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=9,ifName=port23 ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=2i,ifOutErrors=0i,ifOutOctets=0i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=3,ifName=port17 ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=2i,ifOutErrors=0i,ifOutOctets=0i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=6,ifName=port20 ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=2i,ifOutErrors=0i,ifOutOctets=0i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=38,ifName=MAT_IZM_LOCAL ifHighSpeed=10000i,ifInErrors=0i,ifInOctets=1103818849i,ifOperStatus=1i,ifOutErrors=0i,ifOutOctets=2262856529i,ifType=135i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=19,ifName=port1 ifHighSpeed=1000i,ifInErrors=0i,ifInOctets=1213700792i,ifOperStatus=1i,ifOutErrors=0i,ifOutOctets=592914413i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=29,ifName=port11 ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=2i,ifOutErrors=0i,ifOutOctets=0i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=37,ifName=SERVER-1 ifHighSpeed=10000i,ifInErrors=0i,ifInOctets=3081660409i,ifOperStatus=1i,ifOutErrors=0i,ifOutOctets=694524308i,ifType=135i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=16,ifName=ssl.root ifAlias="SSL VPN interface",ifHighSpeed=0i,ifInErrors=0i,ifInOctets=734874827i,ifOperStatus=1i,ifOutErrors=0i,ifOutOctets=1742531827i,ifType=131i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=32,ifName=port14 ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=2i,ifOutErrors=0i,ifOutOctets=0i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=5,ifName=port19 ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=2i,ifOutErrors=0i,ifOutOctets=0i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=31,ifName=port13 ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=2i,ifOutErrors=0i,ifOutOctets=0i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=4,ifName=port18 ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=2i,ifOutErrors=0i,ifOutOctets=0i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=28,ifName=port10 ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=2i,ifOutErrors=0i,ifOutOctets=0i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=39,ifName=WATCHGUARD_INT ifHighSpeed=0i,ifInErrors=0i,ifInOctets=3147374000i,ifOperStatus=1i,ifOutErrors=0i,ifOutOctets=4009845832i,ifType=209i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=1,ifName=mgmt ifHighSpeed=1000i,ifInErrors=0i,ifInOctets=125230892i,ifOperStatus=1i,ifOutErrors=0i,ifOutOctets=60i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=35,ifName=naf.root ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=1i,ifOutErrors=0i,ifOutOctets=152i,ifType=131i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=13,ifName=x3 ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=2i,ifOutErrors=0i,ifOutOctets=0i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=34,ifName=port16 ifHighSpeed=1000i,ifInErrors=0i,ifInOctets=3147374000i,ifOperStatus=1i,ifOutErrors=0i,ifOutOctets=4009846012i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=27,ifName=port9 ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=2i,ifOutErrors=0i,ifOutOctets=0i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=20,ifName=port2 ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=2i,ifOutErrors=0i,ifOutOctets=0i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=15,ifName=modem ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=2i,ifOutErrors=0i,ifOutOctets=0i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=22,ifName=port4 ifHighSpeed=1000i,ifInErrors=0i,ifInOctets=3565906062i,ifOperStatus=1i,ifOutErrors=0i,ifOutOctets=2295644705i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=2,ifName=ha ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=2i,ifOutErrors=0i,ifOutOctets=0i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=12,ifName=x2 ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=2i,ifOutErrors=0i,ifOutOctets=0i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=26,ifName=port8 ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=2i,ifOutErrors=0i,ifOutOctets=0i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=8,ifName=port22 ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=2i,ifOutErrors=0i,ifOutOctets=0i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=23,ifName=port5 ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=2i,ifOutErrors=0i,ifOutOctets=0i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=40,ifName=INTERNET ifHighSpeed=0i,ifInErrors=0i,ifInOctets=906133317i,ifOperStatus=1i,ifOutErrors=0i,ifOutOctets=592914323i,ifType=209i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=14,ifName=x4 ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=2i,ifOutErrors=0i,ifOutOctets=0i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=11,ifName=x1 ifHighSpeed=10000i,ifInErrors=0i,ifInOctets=1651790934i,ifOperStatus=1i,ifOutErrors=0i,ifOutOctets=464164538i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=17,ifName=lan ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=2i,ifOutErrors=0i,ifOutOctets=0i,ifType=209i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=24,ifName=port6 ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=2i,ifOutErrors=0i,ifOutOctets=0i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=18,ifName=fortilink ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=2i,ifOutErrors=0i,ifOutOctets=0i,ifType=161i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=25,ifName=port7 ifHighSpeed=0i,ifInErrors=0i,ifInOctets=0i,ifOperStatus=2i,ifOutErrors=0i,ifOutOctets=0i,ifType=6i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=43,ifName=MATEXEC ifHighSpeed=10000i,ifInErrors=0i,ifInOctets=1504364849i,ifOperStatus=1i,ifOutErrors=0i,ifOutOctets=1801750907i,ifType=135i 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=39 ip="192.168.10.1",net_mask="255.255.255.0" 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=42 ip="10.135.0.1",net_mask="255.255.254.0" 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=41 ip="192.168.6.1",net_mask="255.255.254.0" 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=40 ip="92.45.63.174",net_mask="255.255.255.252" 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=37 ip="192.168.2.1",net_mask="255.255.254.0" 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=18 ip="169.254.1.1",net_mask="255.255.255.0" 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=17 ip="10.0.0.1",net_mask="255.255.248.0" 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=38 ip="10.35.0.1",net_mask="255.255.248.0" 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=1 ip="192.168.5.49",net_mask="255.255.254.0" 1685949049000000000
> MAT,agent_host=192.168.2.1,host=mat-tr-mntr,ifIndex=43 ip="10.235.0.1",net_mask="255.255.0.0" 1685949049000000000
> MAT,agent_host=192.168.2.1,ha_stats_index=1,host=mat-tr-mntr ha_stats_cpu_usage=0i,ha_stats_memory_usage=0i,ha_stats_net_usage=0i,ha_stats_ses_count=0i,ha_stats_sync_status=0i 1685949049000000000

Looks like there are no errors while testing but I got "No data" on the dashboard I've just imported from your repo. What might I am missing?

EDIT: Here a sample of an error from dashboard

Hostname:

Status: 500. Message: invalid: compilation failed: error @1:13-1:21: string literal key uptime must have a value error @1:35-1:62: expected comma in property list, got ASSIGN error @1:42-1:61: string literal key host must have a value error @1:49-1:61: invalid expression @1:60-1:61: ' error @1:49-1:61: unexpected token for property key: ASSIGN (=) error @1:67-1:68: invalid statement: $ error @1:93-1:95: unexpected token for property key: DURATION (1m) error @1:96-1:97: invalid statement:

**Comment by sinankizar** [comment]
Hello and again THANK YOU SO MUCH!

I got it work for me by adding another datasource as InfluxQL. Everything works well.
Can we see VPN users on the dashboard? If we can, how to add the query?

Thanks again

**Comment by amir-am** [comment]
> Hello and again THANK YOU SO MUCH!
> 
> I got it work for me by adding another datasource as InfluxQL. Everything works well. Can we see VPN users on the dashboard? If we can, how to add the query?
> 
> Thanks again

You're welcome. In order to illustrate the VPN Users, you should configure a http plugin in telegraf like this:

```
[[inputs.http]]
  name_override = "YOUR-NAME"
  urls = ['https://YOUR-FIREWALL-DOMAIN/api/v2/monitor/fortiview/statistics?count=100&device=disk&filter={"srcintf":"ssl.Internet"}&ip_version=ipboth&realtime=true&report_by=source&sort_by=bytes&vdom=Internet']
  timeout = "10s"
  method = "GET"
  data_format = "json"
  insecure_skip_verify = true
  tag_keys = ["srcaddr"]
  json_string_fields = ["username"]
  json_query = "results.details"
  tagexclude = ["url"]
  interval = "1m"
  headers = {"Authorization" = "Bearer YOUR-TOKEN"}
```

and then in Table panel, write this query in influxQL:

`SELECT "username" FROM "YOUR-NAME" WHERE $timeFilter GROUP BY "srcaddr" LIMIT 1`

I hope this work for you.

**Comment by sinankizar** [comment]
Hello agan,
Thanks for your reply but I got lost in:
"username" and "YOUR-TOKEN"

Where should I get those?

Edit:

I think: YOUR-NAME = that we had set up in first telegraf.conf
username: fortigate rest api admin
YOUR-TOKEN= fortigate rest api token

Is this correct? If it is I have entered those to telegraf config but test gave me an error:

Error in plugin: [url=https://192.168.2.1/api/v2/monitor/fortiview/statistics?count=100&device=disk&filter={"srcintf":"ssl.Internet"}&ip_version=ipboth&realtime=true&report_by=source&sort_by=bytes&vdom=Internet]: Get "https://192.168.2.1/api/v2/monitor/fortiview/statistics?count=100&device=disk&filter={\"srcintf\":\"ssl.Internet\"}&ip_version=ipboth&realtime=true&report_by=source&sort_by=bytes&vdom=Internet": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by sinankizar** [comment]
Hello again,

I think I have managed to get the conf file working, I am not getting any errors when I put the url this way:

https://192.168.2.1:1443/api/v2/monitor/fortiview/statistics?count=100&device=disk&filter={"srcintf":"vpn.ssl"}&ip_version=ipboth&realtime=true&report_by=source&sort_by=bytes&vdom=root

When I put this line into browsers address bar, I got this:

{
  "http_method":"GET",
  "results":{
    "details":[
    ]
  },
  "vdom":"root",
  "path":"fortiview",
  "name":"statistics",
  "action":"",
  "status":"success",
  "serial":"MY_UNIT_SERIAL",
  "version":"v7.2.4",
  "build":1396
}



But the query returns with error "invalid statement"

![image](https://github.com/amir-am/Firewall-Monitoring/assets/28201097/31a53f03-f241-40c3-9c84-8407df89ea3e)

**Comment by sinankizar** [comment]
I had all the data and it is working perfect except vpn users. Thank you again..
